'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ClassroomAttendance.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _105_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("105-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _14516142_update_icon_on_glossy_orange_round_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14516142-update-icon-on-glossy-orange-round-button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _14516142_update_icon_on_glossy_orange_round_button1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14516142-update-icon-on-glossy-orange-round-button1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _21936872_Training_icon_Stock_Vector_presentation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21936872-Training-icon-Stock-Vector-presentation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9396080_Pulsante_Aggiorna_lucido_Archivio_Fotografico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9396080-Pulsante-Aggiorna-lucido-Archivio-Fotografico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property conference_room() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conference-room", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contact_details__ios_7_interface_symbol_318_33582() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contact-details--ios-7-interface-symbol_318-33582", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eliminar_simbolo_de_contacto_para_la_interfaz_318_46960() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eliminar-simbolo-de-contacto-para-la-interfaz_318-46960", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jadwal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jadwal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jadwal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jadwal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Knowledge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Knowledge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Knowledge1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Knowledge1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout__ios_7_interface_symbol_318_33643() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout--ios-7-interface-symbol_318-33643", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout__ios_7_interface_symbol_318_336431() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout--ios-7-interface-symbol_318-336431", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_alt_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu-alt-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_alt_5121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu-alt-5121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_alt_5122() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu-alt-5122", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_alt_5123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu-alt-5123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notification_remove__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notification_remove (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_plus_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red-plus-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_vector_vector_illustration_of_a_checklist_with_a_detailed_pencil_checking_off_tasks_126009953() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-vector-vector-illustration-of-a-checklist-with-a-detailed-pencil-checking-o"& _ 
                        "ff-tasks-126009953", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
